webshop-in-csharp/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebshopInCsharp.Models;
using Microsoft.AspNetCore.Identity;
using WebshopInCsharp.Models.Identity;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace WebshopInCsharp.Controllers
{
    public class ProfileController : Controller
    {
        private readonly ApplicationDbContext _context;

        private UserManager<User> _userManager;

        private IHostingEnvironment _environment;

        public ProfileController(ApplicationDbContext context, UserManager<User> userManager, IHostingEnvironment environment)
        {
            _context = context;
            _userManager = userManager;
            _environment = environment;
        }
        
        // GET: Profile/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles
                .SingleOrDefaultAsync(m => m.Id == id);
            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        [HttpGet]
        public IActionResult Search()
        {
            ProfileSearchViewModel vm = new ProfileSearchViewModel();
            vm.MinAge = 18;
            vm.MaxAge = 85;

            return View(vm);
        }

        [HttpPost]
        public IActionResult Search(ProfileSearchViewModel vm)
        {
            List<ProfileSearchResultModel> result = new List<ProfileSearchResultModel>();
            if (ModelState.IsValid)
            {
                DateTime minDate = DateTime.Today.AddYears(-vm.MaxAge);
                DateTime maxDate = DateTime.Today.AddYears(-vm.MinAge);

                result = (from p in _context.Profiles
                          where p.Gender == vm.Gender
                          && p.Birthdate > minDate && p.Birthdate < maxDate
                          select new ProfileSearchResultModel
                          {
                              Description = p.Description,
                              Id = p.Id,
                              ProfilePicture = $"{p.User.Id}/{p.ProfilePicture}",
                              Gender = p.Gender,
                              DisplayName = p.DisplayName,
                              Age = calculateAge(p.Birthdate)
                          }
                          ).ToList();
            }
            return View("Result", result);
        }
        
        private int calculateAge(DateTime birthDate)
        {
            int age = DateTime.Today.Year - birthDate.Year;
            if (birthDate > DateTime.Today.AddYears(-age))
            {
                age--;
            }
            return age;
        }

        // GET: Profile/Edit/5
        public async Task<IActionResult> Edit()
        {
            User currentUser = await _userManager.GetUserAsync(User);
            var profile = await _context.Profiles.SingleOrDefaultAsync(m => m.Id == currentUser.ProfileId);
            return View(profile);
        }

        // POST: Profile/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,DisplayName,Birthdate,Description,ProfilePicture,ProfilePictureFile ")] Profile profile, IFormFile ProfilePictureFile)
        {
            if (ModelState.IsValid)
            {
                User currentUser = await _userManager.GetUserAsync(User);

                if(ProfilePictureFile != null)
                {
                    string uploadPath = Path.Combine(_environment.WebRootPath, "uploads");
                    Directory.CreateDirectory(Path.Combine(uploadPath, currentUser.Id));

                    string filename = Path.GetFileName(ProfilePictureFile.FileName);

                    using (FileStream fs = new FileStream(Path.Combine(uploadPath, currentUser.Id, filename), FileMode.Create))
                    {
                        await ProfilePictureFile.CopyToAsync(fs);
                    }
                    profile.ProfilePicture = filename;
                }


                _context.Update(profile);
                await _context.SaveChangesAsync();
            }
            return View(profile);
        }

        // GET: Profile/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles
                .SingleOrDefaultAsync(m => m.Id == id);
            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        // POST: Profile/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var profile = await _context.Profiles.SingleOrDefaultAsync(m => m.Id == id);
            _context.Profiles.Remove(profile);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ProfileExists(int id)
        {
            return _context.Profiles.Any(e => e.Id == id);
        }
    }
}

webshop-in-csharp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewBag.Title</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Wannabe Webshop</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li><a href="@Url.Action("Edit", "Profile")">My Profile</a></li>
                        <li><a href ="@Url.Action("Search", "Profile")">Search</a></li>
                        <li><a>@User.Identity.Name</a></li>

                        


                    }
                    else
                    {
                        <li><a href="@Url.Action("Register", "Account")">Register account</a></li>
                        <li><a href="@Url.Action("Login", "Account")">Login</a></li>
                    }
                </ul>

                @if (SignInManager.IsSignedIn(User))
                {
                    <li class="pull-right"><button class="btn btn-default"><a href="@Url.Action("Logout", "Account")">Logout</a></button> </li>
                }
            </div><!--/.nav-collapse -->
        </div>

            
    </nav>

    <div class="container">
        @RenderBody()
    </div>
    </div><!-- /.container -->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    @RenderSection("Scripts", false)
</body>
</html>